---
- name: Cassandra | General setup | install java runtime
  hosts: localhost
  tasks:
    - name: Cassandra | General setup | APT Repo 
      apt_repository:
        repo: 'ppa:openjdk-r/ppa'
        state: present
      become: true
      become_method: sudo

    - name: Cassandra | General setup | Install general apps
      apt: 
        name: "{{ item }}"
        update_cache: yes
        state: present
      become: true
      become_method: sudo
      with_items:
        - vim
        - curl
        - zip
        - unzip
        - git
        - python-pip

    - name: Cassandra | General setup | Install java JDK
      apt: 
        name: "{{ item }}"
        update_cache: yes
        state: present
      become: true
      become_method: sudo
      with_items:
        - openjdk-8-jdk
    
    - name: Cassandra | General setup | Install cassandra-driver
      pip:
        name: cassandra-driver
        state: present 

    - name: Cassandra | General setup | Set environment variable
      shell: echo 'export CQLSH_NO_BUNDLED=TRUE' >> ~/.profile  